// flow-typed signature: 8458c830e2cb0b001e834f8c30e3ae2b
// flow-typed version: <<STUB>>/travis-github-status_v^1.4.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'travis-github-status'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'travis-github-status' {
  declare module.exports: any

  /**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
}
declare module 'travis-github-status/dist/index' {
  declare module.exports: any

  // Filename aliases
}
declare module 'travis-github-status/dist/index.js' {
  declare module.exports: $Exports<'travis-github-status/dist/index'>
}
